# ### LOADING LIBRARIES ### -----------------------------------------------

#BECAUSE EVERY PACKAGE USED MUST BE INSTALLED ON THE INSTANCE WITH EVERY DEPLOYMENT, WE WANT TO MINIMIZE THE NUMBER OF PACKAGES USED IN TOTAL. HERE ARE THE ONES I GENERALLY CONSIDER TO BE ESSENTIAL. DELETE ANY NOT NEEDED. ADD ANY THAT ARE ESSENTIAL IN YOUR CONTEXT.

library(shiny) #ESSENTIAL.
library(dplyr) #DATA MANIPULATION.
library(stringr) #STRING MANIPULATION.
library(gargle) #GOOGLE DRIVE AUTHETICATION.
library(googledrive) #GOOGLE DRIVE INTERACTIONS.
library(googlesheets4) #GOOGLE SHEETS INTERACTIONS.
library(shinyjs) #COMMON JAVASCRIPT OPERATIONS.
library(DT) #DT TABLES
library(waiter) #WAITERS, SPINNERS, AND PRELOADERS.
library(sf) #WORKING W/ SPATIAL DATA FOR MAPS (IF USING LEAFLET)
library(leaflet) #LEAFLET MAPS
library(shinydisconnect) #CUSTOM DISCONNECT SCREEN.
library(plotly) #PLOTLY GRAPHS
library(viridis) #COLORBLIND-FRIENDLY PALETTES


# ### SETTING GLOBAL OPTIONS ### ------------------------------------------

#IN GENERAL, I DON'T DO MUCH HERE, BUT I DO SET UP CONNECTIONS TO GOOGLE DRIVE HERE AS NEEDED. REMOVE THESE IF THEY ARE IRRELEVANT TO YOU.

#SET SCOPES FOR WHAT OUR GOOGLE APIS WILL BE ALLOWED TO DO
sheets_scope <- "https://www.googleapis.com/auth/spreadsheets"
drive_scope <- "https://www.googleapis.com/auth/drive"

#SET FILE PATH TO THE GOOGLE SERVICE ACCOUNT TOKEN
sa_key_path <- "PI_Survey/.secrets/picharter-57080685c8d0.json"

#DON'T TRY TO AUTHENTICATE USING STANDARD TOKENS.
options(
  gargle_oauth_cache = FALSE
  )

#AUTHENTICATE USING OUR JSON TOKEN ATTACHED TO OUR GOOGLE SERVICE ACCOUNT W/ PROPER SCOPES
drive_auth(path = sa_key_path, scopes = c(sheets_scope, drive_scope))

#ALSO AUTHENTICATE TO GOOGLE SHEETS SPECIFICALLY
googlesheets4::gs4_auth(path = sa_key_path, scopes = c(sheets_scope, drive_scope))


# ### LOAD MODULES ### ----------------------------------------------------

#IF YOU HAVE MODULARIZED THE APP, LOAD THE MODULE FILES HERE.

source("Rcode/Modules/ExampleServer.R")
source("Rcode/Modules/ExampleUI.R")



#  ### ESTABLISH CONVENIENCE FUNCTIONS ### --------------------------------

#I HAVE SEVERAL CONVENIENCE FUNCTIONS THAT I OFTEN SEEM TO NEED IN MY SHINY APPS. I'VE STORED THESE IN A SINGLE FILE THAT I SOURCE HERE. ANY MORE "NICHE" ONES I WRITE OUT HERE.

source("Rcode/Scripts/shinyConvenienceFunctions.R")
 

# ### LOAD NECESSARY INPUTS ### -------------------------------------------

#MOST SHINY APPS DEPEND UPON AT LEAST SOME OUTSIDE DATA. LOAD THAT HERE. I'VE INCLUDED SOME THINGS HERE I REGULARLY NEED--DELETE ANY THAT ARE IRRELEVANT AND REMOVE THE RESPECTIVE FILES FROM THE INPUTS FOLDER.

#I SO REGULARLY NEED TO KNOW THE NAMES/DOWS/COUNTIES OF LAKES IN MN THAT I'VE COMBINED ALL THAT INTO A SINGLE DF, LOADED HERE.
dows_lakenames_counties = read.csv("inputs/Static/dows_lakenames_counties.csv", colClasses = "character")

#THIS OBJECT IS A LIST OF ALL THE LAKE DOWS THAT ARE ON TRIBAL LANDS IN THE STATE.
tribal_DOWs = readRDS("inputs/Static/tribal_DOWs.rds") 

#AN OUTLINE OF THE STATE OF MINNESOTA FOR MAPS.
MN = readRDS("inputs/Static/MN") 

#HERE IS SOME SAMPLE CODE FOR GETTING THE SHEET ID FOR A GOOGLE SHEET, IN CASE YOU NEED TO "TALK" TO ONE. 
 metadata_id = googledrive::drive_get("[SHARING LINK]")$id


# ### PRE-BAKE GLOBAL ENVIRONMENT OBJECTS ### -----------------------------

#ANY OPERATIONS THAT CAN BE AVOIDED DURING APP OPERATION BY PERFORMING THEM ON LAUNCH ("PRE-BAKING") IMPROVES USER EXPERIENCE. IDEALLY, THESE WOULD BE FASHIONED UPSTREAM AND SIMPLY LOADED IN THE PREVIOUS SECTION, BUT SOMETIMES, THESE CHANGE OFTEN ENOUGH THAT IT'S MORE CONVENIENT TO DO THOSE OPERATIONS HERE, IF THEY ARE SPEEDY ENOUGH.
